### ISSUE TITLE
Append variables to an environment, don't override if there are multiple environments with the same name

### ISSUE THREAD

**Issue by barnabyalter** [NYULibraries/figs#19]
Specifically when the `Figsfile` contains something like the following:

```yaml
--- !ruby/object:Figs::Figsfile
repo: git@github.com:NYULibraries/configula.git
method: git
locations:
- common
- exlibris-nyu.yml
- getit.yml
```

And the file `exlibris-nyu.yml` contains something that looks like:

```yaml
production:
   ALEPH_URL: ...
```

And `getit.yml` also has a production environment. Depending on load order it varies but at the end of the day when doing things like this it would be nice if `Figs.env.production` would contain all the production variables from all the files that have a production environment, not just one of them.

Thoughts?
